consul-conf:
  image: sundeer/docker-consul-config:feature_test
  labels:
    io.rancher.container.hostname_override: container_name
  volumes_from:
    - consul
  net: "container:consul"

consul:
  image: sundeer/docker-consul-server:feature_test
  labels:
    io.rancher.sidekicks: consul-conf
  volumes:
    - /opt/rancher/ssl
    - /opt/rancher/config
    - /var/consul
