lb:
  image: rancher/load-balancer-service
  expose:
    - 8500:8500/tcp
  tty: true
  stdin_open: true
  links:
    - server-1:server-1
    - server-2:server-2
    - server-3:server-3

server-1:
  image: sundeer/rancher-consul:latest
  command: '-server -config-file /config/server.json -advertise 10.42.16.1 -bootstrap-expect 3'
  labels:
    io.rancher.container.requested_ip: 10.42.16.1

server-2:
  image: sundeer/rancher-consul:latest
  command: '-server -config-file /config/server.json -advertise 10.42.16.2 -join server-1'
  labels:
    io.rancher.container.requested_ip: 10.42.16.2

server-3:
  image: sundeer/rancher-consul:latest
  command: '-server -config-file /config/server.json -advertise 10.42.16.3 -join server-1'
  labels:
    io.rancher.container.requested_ip: 10.42.16.3
