config:
  image: sundeer/docker-consul-config:feature_refactor
  labels:
    io.rancher.container.hostname_override: container_name
  volumes_from:
    - server
  net: "container:server"

server:
  image: sundeer/docker-consul-server:feature_test
  labels:
    io.rancher.sidekicks: config
    io.rancher.container.hostname_override: container_name
  volumes:
    - /opt/rancher/ssl
    - /opt/rancher/config
    - /var/consul
