consul:
  image: rancher/dns-service
  links:
  - server:server

server:
  image: sundeer/docker-consul-server:feature_use-hc-dockerfile
  command: server -bind=0.0.0.0
  labels:
    io.rancher.sidekicks: config
    io.rancher.container.hostname_override: container_name
  volumes:
    - /app/config

config:
  image: sundeer/docker-consul-config:feature_refactor
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  volumes_from:
    - server
  net: "container:server"
