consul:
  image: rancher/dns-service
  links:
  - server:server

server:
  image: sundeer/docker-consul-server:latest
  command: server -bind=0.0.0.0
  labels:
    io.rancher.sidekicks: config
    io.rancher.container.hostname_override: container_name
  volumes:
    - /app/config

config:
  image: sundeer/docker-consul-config:latest
  environment:
    CA_CRT:
    CONSUL1_CRT:
    CONSUL_KEY:
    ENC_KEY:
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  volumes_from:
    - server
  net: "container:server"
